### ISSUE TITLE
Не работает должным образом sleepingowl:install

### ISSUE THREAD

**Issue by xvladxtremal** [LaravelRUS/SleepingOwlAdmin#328]
Не работало sleepingowl:install, сделал добавлением в App/Console/Kernel.php
`    protected $commands = [
        \SleepingOwl\Admin\Commands\InstallCommand::class,
        \SleepingOwl\Admin\Commands\UserManagerCommand::class,
        \SleepingOwl\Admin\Commands\SectionGenerate::class,
        \SleepingOwl\Admin\Commands\SectionMake::class,
        \SleepingOwl\Admin\Commands\SectionProvider::class,
    ];`
В итоге команда срабатывает, но папка app/admin не создается, конфиг не публикуется.

>  php artisan sleepingowl:install
Nothing to publish for tag [].
Admin bootstrap directory was created:
File AdminSectionsServiceProvider exists

Сервис провайдер в app.php добавил
Проверял на laravel 5.2.45, 5.2.3, 5.2.31, sleppingowl 4.*@dev, 4.60.13, 4.60.00
Windows 10, OpenServer, проверял на php 5.6, 7

**Comment by xvladxtremal** [comment]
Log:

> [2016-10-31 14:39:50] local.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: There are no commands defined in the "sleepingowl" namespace. in C:\OpenServer\domains\frsdev.local\vendor\symfony\console\Application.php:469
Stack trace:
#0 C:\OpenServer\domains\frsdev.local\vendor\symfony\console\Application.php(501): Symfony\Component\Console\Application->findNamespace('sleepingowl')
#1 C:\OpenServer\domains\frsdev.local\vendor\symfony\console\Application.php(183): Symfony\Component\Console\Application->find('sleepingowl:ins...')
#2 C:\OpenServer\domains\frsdev.local\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\OpenServer\domains\frsdev.local\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\OpenServer\domains\frsdev.local\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}

**Comment by xvladxtremal** [comment]
По-моему проблема с сервис контейнером, или композером. Не видит неймспейсы пакета.

**Comment by xvladxtremal** [comment]
На чистой Ларе всё ОК. Отсюда вывод, что я что-то поломал.Закрывай.
